version: "3.8"

services:
  backend:
    build: ./Backend-Code
    ports:
      - "5001:5001"
    restart: always

  frontend:
    build:
      context: ./frontend-code/react-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always