import { useState, useEffect, useRef } from "react";
import { FloorPlanStaticObjects } from "./AlarmObj.tsx";
import alarmSound from "../assets/alarmSound.wav";
import "../css/Alarms.css";

// A simple point in percentage relative to the floor plan.
type Point = {
  x: number;
  y: number;
};

// Updated AlarmZone with a unique ID generated by the backend.
type AlarmZone = {
  id: string;
  topLeft: Point;
  bottomRight: Point;
  active: boolean;
  triggered: boolean;
};

// Set this to match your backend host and port.
const BACKEND_URL = "http://localhost:5001";

export const LarmData = () => {
  // Mode control: 0 - Add Zone, 1 - Remove Zone, 2 - Zone Status
  const [activeIndexLB, setActiveIndex] = useState(0);
  // The starting point for a new zone.
  const [zoneStart, setZoneStart] = useState<Point | null>(null);
  // A draft zone drawn while moving the mouse. Note: Excludes the id.
  const [draftZone, setDraftZone] = useState<Omit<AlarmZone, "id"> | null>(
    null
  );
  // List of finalized alarm zones that include their ID.
  const [alarms, setAlarms] = useState<AlarmZone[]>([]);

  // Audio ref for alarm sound
  const audioRef = useRef<HTMLAudioElement>(null);

  // Fetch existing alarm zones from the backend when the component mounts.
  useEffect(() => {
    // Fetch immediately, then every 100ms
    fetchAlarms();
    const intervalId = setInterval(fetchAlarms, 100);

    // Cleanup on unmount
    return () => clearInterval(intervalId);
  }, []);

  // Play/pause alarm sound when any zone is triggered
  useEffect(() => {
    const anyTriggered = alarms.some((zone) => zone.triggered);
    const audio = audioRef.current;
    if (audio) {
      if (anyTriggered) {
        audio.play().catch((e) => console.warn("Audio play failed:", e));
      } else {
        audio.pause();
        audio.currentTime = 0;
      }
    }
  }, [alarms]);

  /**
   * API call for all Alarms.
   * gets the list of alarms
   */
  const fetchAlarms = async () => {
    try {
      const res = await fetch(`${BACKEND_URL}/api/alarms`);
      if (!res.ok) {
        throw new Error("Failed to fetch alarms from backend");
      }
      const data = await res.json();
      if (data.alarms) {
        setAlarms(data.alarms);
        console.log("Loaded alarms from backend:", data.alarms);
      }
    } catch (err) {
      console.error("Error fetching alarms:", err);
    }
  };

  // Handle switching modes. If leaving Add Zone mode, clear drawing state.
  const handleButtonClick = (index: number) => {
    setActiveIndex(index);
    if (index !== 0) {
      setZoneStart(null);
      setDraftZone(null);
    }
  };

  // Compute an AlarmZone from two points without generating an ID.
  const calculateAlarmZone = (p1: Point, p2: Point): Omit<AlarmZone, "id"> => {
    const topLeft = { x: Math.min(p1.x, p2.x), y: Math.min(p1.y, p2.y) };
    const bottomRight = { x: Math.max(p1.x, p2.x), y: Math.max(p1.y, p2.y) };
    return { topLeft, bottomRight, active: true, triggered: false };
  };

  const changeAlarmStatus = (id: string) => {
    fetch(`${BACKEND_URL}/api/alarms/status/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
    })
      .then((response) => {
        if (!response.ok) throw new Error("Failed to update alarm");
        return response.json();
      })
      .then((result) => {
        console.log("Backend response:", result);
        setAlarms((prev) =>
          prev.map((alarm) =>
            alarm.id === id ? { ...alarm, active: !alarm.active } : alarm
          )
        );
      })
      .catch((err) => console.error("Error updating alarm:", err));
  };

  // Save a new alarm zone via a POST call to the backend.
  const saveAlarmZone = (newAlarm: Omit<AlarmZone, "id">) => {
    fetch(`${BACKEND_URL}/api/alarms`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(newAlarm),
    })
      .then((response) => {
        if (!response.ok) throw new Error("Failed to save alarm zone");
        return response.json();
      })
      .then((data) => {
        if (data.alarm) {
          setAlarms((prev) => [...prev, data.alarm]);
          console.log("Saved new alarm zone:", data.alarm);
        }
      })
      .catch((err) => console.error("Error saving alarm zone:", err));
  };

  // Remove an alarm zone via a DELETE call to the backend.
  const handleRemoveZone = (id: string) => {
    fetch(`${BACKEND_URL}/api/alarms/${id}`, { method: "DELETE" })
      .then((response) => {
        if (!response.ok) throw new Error("Failed to remove alarm zone");
        return response.json();
      })
      .then(() => {
        setAlarms((prev) => prev.filter((alarm) => alarm.id !== id));
        console.log("Removed alarm zone with id:", id);
      })
      .catch((err) => console.error("Error removing alarm zone:", err));
  };

  // Handle left-click events for Add Zone mode.
  const handleMouseClick = (
    e: React.MouseEvent<HTMLDivElement, MouseEvent>
  ) => {
    if (activeIndexLB !== 0) return;
    const rect = e.currentTarget.getBoundingClientRect();
    const x = ((e.clientX - rect.left) / rect.width) * 100;
    const y = ((e.clientY - rect.top) / rect.height) * 100;
    const point = { x, y };

    if (!zoneStart) {
      setZoneStart(point);
    } else {
      const zone = calculateAlarmZone(zoneStart, point);
      saveAlarmZone(zone);
      setZoneStart(null);
      setDraftZone(null);
    }
  };

  // Update the draft zone dynamically as the mouse moves.
  const handleMouseMove = (e: React.MouseEvent<HTMLDivElement>) => {
    if (activeIndexLB !== 0 || !zoneStart) return;
    const rect = e.currentTarget.getBoundingClientRect();
    const point = {
      x: ((e.clientX - rect.left) / rect.width) * 100,
      y: ((e.clientY - rect.top) / rect.height) * 100,
    };
    setDraftZone(calculateAlarmZone(zoneStart, point));
  };

  // Right-click cancels the current draft.
  const handleContextMenu = (e: React.MouseEvent<HTMLDivElement>) => {
    if (activeIndexLB === 0 && zoneStart) {
      e.preventDefault();
      setZoneStart(null);
      setDraftZone(null);
    }
  };

  return (
    <div className="alarmsDiv">
      {/* Alarm sound element */}
      <audio ref={audioRef} src={alarmSound} loop preload="auto" />

      <div className="alarmLeftSidebar">
        {/* Sidebar buttons */}
        <button
          className={`alarmButton ${activeIndexLB === 0 ? "active" : ""}`}
          onClick={() => handleButtonClick(0)}
        >
          Add Zone
        </button>
        <button
          className={`alarmButton ${activeIndexLB === 1 ? "active" : ""}`}
          onClick={() => handleButtonClick(1)}
        >
          Remove Zone
        </button>
        <button
          className={`alarmButton ${activeIndexLB === 2 ? "active" : ""}`}
          onClick={() => handleButtonClick(2)}
        >
          Zone Status
        </button>
      </div>
      <div className="mapDiv">
        <div
          className="mapDiv2"
          style={{ position: "relative" }}
          onClick={handleMouseClick}
          onMouseMove={handleMouseMove}
          onContextMenu={handleContextMenu}
        >
          <FloorPlanStaticObjects />

          {/* Draft zone while drawing */}
          {draftZone && (
            <div
              style={{
                position: "absolute",
                left: `${draftZone.topLeft.x}%`,
                top: `${draftZone.topLeft.y}%`,
                width: `${draftZone.bottomRight.x - draftZone.topLeft.x}%`,
                height: `${draftZone.bottomRight.y - draftZone.topLeft.y}%`,
                backgroundColor: "rgba(144,238,144,0.5)",
                pointerEvents: "none",
                border: "2px dashed green",
              }}
            />
          )}

          {/* Render alarm zones */}
          {alarms.map((zone) => (
            <div
              key={zone.id}
              onClick={
                activeIndexLB === 1 || activeIndexLB === 2
                  ? (e) => {
                      e.stopPropagation();
                      activeIndexLB === 1
                        ? handleRemoveZone(zone.id)
                        : changeAlarmStatus(zone.id);
                    }
                  : undefined
              }
              className={`alarmZone ${
                zone.triggered
                  ? "blinking"
                  : zone.active
                  ? "active"
                  : "inactive"
              }`}
              style={{
                left: `${zone.topLeft.x}%`,
                top: `${zone.topLeft.y}%`,
                width: `${zone.bottomRight.x - zone.topLeft.x}%`,
                height: `${zone.bottomRight.y - zone.topLeft.y}%`,
              }}
            />
          ))}
        </div>
      </div>
    </div>
  );
};

export default LarmData;
