import { useState, useEffect, useRef } from "react";
import { FloorPlanStaticObjects } from "./AlarmObj.tsx";
import alarmSound from "../assets/alarmSound.wav";
import "../css/Alarms.css";

// A simple point in percentage relative to the floor plan.
type Point = {
  x: number;
  y: number;
};

// Updated AlarmZone with a unique ID generated by the backend.
type AlarmZone = {
  id: string;
  topLeft: Point;
  bottomRight: Point;
  active: boolean;
  triggered: boolean;
};

// Set this to match your backend host and port.
const BACKEND_URL = "http://localhost:5001";

export const LarmData = () => {
  // Mode control: 0 - Add Zone, 1 - Remove Zone, 2 - Zone Status
  const [activeIndexLB, setActiveIndex] = useState(0);
  // The starting point for a new zone.
  const [zoneStart, setZoneStart] = useState<Point | null>(null);
  // A draft zone drawn while moving the mouse. Note: Excludes the id.
  const [draftZone, setDraftZone] = useState<Omit<AlarmZone, "id"> | null>(null);
  // List of finalized alarm zones that include their ID.
  const [alarms, setAlarms] = useState<AlarmZone[]>([]);
  // Track saving state for loading message
  const [isLoading, setIsLoading] = useState(false);

  // Audio ref for alarm sound
  const audioRef = useRef<HTMLAudioElement>(null);

  // Fetch existing alarm zones from the backend when the component mounts.
  useEffect(() => {
    fetchAlarms();
    const intervalId = setInterval(fetchAlarms, 500);
    return () => clearInterval(intervalId);
  }, []);

  // Play/pause alarm sound when any zone is triggered
  useEffect(() => {
    const anyTriggered = alarms.some((zone) => zone.triggered);
    const audio = audioRef.current;
    if (audio) {
      if (anyTriggered) {
        audio.play().catch((e) => console.warn("Audio play failed:", e));
      } else {
        audio.pause();
        audio.currentTime = 0;
      }
    }
  }, [alarms]);

  const fetchAlarms = async () => {
    try {
      const res = await fetch(`${BACKEND_URL}/api/alarms`);
      if (!res.ok) {
        throw new Error("Failed to fetch alarms from backend");
      }
      const data = await res.json();
      if (data.alarms) {
        setAlarms((prev) => {
          const optimisticAlarms = prev.filter((alarm) =>
            alarm.id.startsWith("temp-")
          );
          const backendAlarms = data.alarms;
          return [...backendAlarms, ...optimisticAlarms];
        });
        console.log("Loaded alarms from backend:", data.alarms);
      }
    } catch (err) {
      console.error("Error fetching alarms:", err);
    }
  };

  const handleButtonClick = (index: number) => {
    setActiveIndex(index);
    if (index !== 0) {
      setZoneStart(null);
      setDraftZone(null);
    }
  };

  const calculateAlarmZone = (p1: Point, p2: Point): Omit<AlarmZone, "id"> => {
    const topLeft = { x: Math.min(p1.x, p2.x), y: Math.min(p1.y, p2.y) };
    const bottomRight = { x: Math.max(p1.x, p2.x), y: Math.max(p1.y, p2.y) };
    return { topLeft, bottomRight, active: true, triggered: false };
  };

  const changeAlarmStatus = (id: string) => {
    setIsLoading(true);
    fetch(`${BACKEND_URL}/api/alarms/status/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
    })
      .then((response) => {
        if (!response.ok) throw new Error("Failed to update alarm");
        setIsLoading(false);
        return response.json();
      })
      .then((result) => {
        console.log("Backend response:", result);
        setAlarms((prev) =>
          prev.map((alarm) =>
            alarm.id === id ? { ...alarm, active: !alarm.active } : alarm
          )
        );
      })
      .catch((err) => console.error("Error updating alarm:", err));
  };

  const saveAlarmZone = (newAlarm: Omit<AlarmZone, "id">) => {
    const tempId = `temp-${Date.now()}`;
    const optimisticAlarm: AlarmZone = { ...newAlarm, id: tempId };
    setAlarms((prev) => [...prev, optimisticAlarm]);
    
    // Set loading state to true
    setIsLoading(true);

    fetch(`${BACKEND_URL}/api/alarms`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(newAlarm),
    })
      .then((response) => {
        if (!response.ok) {
          setAlarms((prev) => prev.filter((alarm) => alarm.id !== tempId));
          throw new Error("Failed to save alarm zone");
        }
        return response.json();
      })
      .then((data) => {
        if (data.alarm) {
          setAlarms((prev) =>
            prev.map((alarm) =>
              alarm.id === tempId ? data.alarm : alarm
            )
          );
          console.log("Saved new alarm zone:", data.alarm);
        }
      })
      .catch((err) => {
        console.error("Error saving alarm zone:", err);
        setAlarms((prev) => prev.filter((alarm) => alarm.id !== tempId));
      })
      .finally(() => {
        // Set loading state to false when the request completes (success or failure)
        setIsLoading(false);
      });
  };

  const handleRemoveZone = (id: string) => {
    setIsLoading(true);
    fetch(`${BACKEND_URL}/api/alarms/${id}`, { method: "DELETE" })
      .then((response) => {
        if (!response.ok) throw new Error("Failed to remove alarm zone");
        setIsLoading(false);
        return response.json();
      })
      .then(() => {
        setAlarms((prev) => prev.filter((alarm) => alarm.id !== id));
        console.log("Removed alarm zone with id:", id);
      })
      .catch((err) => console.error("Error removing alarm zone:", err));
  };

  const handleMouseClick = (
    e: React.MouseEvent<HTMLDivElement, MouseEvent>
  ) => {
    if (activeIndexLB !== 0) return;
    const rect = e.currentTarget.getBoundingClientRect();
    const x = ((e.clientX - rect.left) / rect.width) * 100;
    const y = ((e.clientY - rect.top) / rect.height) * 100;
    const point = { x, y };

    if (!zoneStart) {
      setZoneStart(point);
    } else {
      const zone = calculateAlarmZone(zoneStart, point);
      saveAlarmZone(zone);
      setZoneStart(null);
      setDraftZone(null);
    }
  };

  const handleMouseMove = (e: React.MouseEvent<HTMLDivElement>) => {
    if (activeIndexLB !== 0 || !zoneStart) return;
    const rect = e.currentTarget.getBoundingClientRect();
    const point = {
      x: ((e.clientX - rect.left) / rect.width) * 100,
      y: ((e.clientY - rect.top) / rect.height) * 100,
    };
    setDraftZone(calculateAlarmZone(zoneStart, point));
  };

  const handleContextMenu = (e: React.MouseEvent<HTMLDivElement>) => {
    if (activeIndexLB === 0 && zoneStart) {
      e.preventDefault();
      setZoneStart(null);
      setDraftZone(null);
    }
  };

  return (
    <div className="alarmsDiv">
      <audio ref={audioRef} src={alarmSound} loop preload="auto" />

      <div className="alarmLeftSidebar">
        <button
          className={`alarmButton ${activeIndexLB === 0 ? "active" : ""}`}
          onClick={() => handleButtonClick(0)}
        >
          Add Zone
        </button>
        <button
          className={`alarmButton ${activeIndexLB === 1 ? "active" : ""}`}
          onClick={() => handleButtonClick(1)}
        >
          Remove Zone
        </button>
        <button
          className={`alarmButton ${activeIndexLB === 2 ? "active" : ""}`}
          onClick={() => handleButtonClick(2)}
        >
          Zone Status
        </button>
      </div>

      <div className="mapDiv">
        <div
          className="mapDiv2"
          style={{ position: "relative" }}
          onClick={handleMouseClick}
          onMouseMove={handleMouseMove}
          onContextMenu={handleContextMenu}
        >
          <FloorPlanStaticObjects />

          {/* Display loading message while saving */}
          {isLoading && (
            <div
              style={{
                position: "absolute",
                top: "50%",
                left: "50%",
                transform: "translate(-50%, -50%)",
                backgroundColor: "rgba(0, 0, 0, 0.7)",
                color: "white",
                padding: "10px 20px",
                borderRadius: "5px",
                zIndex: 10,
              }}
            >
              Loading...
            </div>
          )}

          {draftZone && (
            <div
              style={{
                position: "absolute",
                left: `${draftZone.topLeft.x}%`,
                top: `${draftZone.topLeft.y}%`,
                width: `${draftZone.bottomRight.x - draftZone.topLeft.x}%`,
                height: `${draftZone.bottomRight.y - draftZone.topLeft.y}%`,
                backgroundColor: "rgba(144,238,144,0.5)",
                pointerEvents: "none",
                border: "2px dashed green",
              }}
            />
          )}

          {alarms.map((zone) => (
            <div
              key={zone.id}
              onClick={
                activeIndexLB === 1 || activeIndexLB === 2
                  ? (e) => {
                      e.stopPropagation();
                      activeIndexLB === 1
                        ? handleRemoveZone(zone.id)
                        : changeAlarmStatus(zone.id);
                    }
                  : undefined
              }
              className={`alarmZone ${
                zone.id.startsWith("temp-") ? "temp" : ""
              } ${
                zone.triggered
                  ? "blinking"
                  : zone.active
                  ? "active"
                  : "inactive"
              }`}
              style={{
                left: `${zone.topLeft.x}%`,
                top: `${zone.topLeft.y}%`,
                width: `${zone.bottomRight.x - zone.topLeft.x}%`,
                height: `${zone.bottomRight.y - zone.topLeft.y}%`,
              }}
            />
          ))}
        </div>
      </div>
    </div>
  );
};

export default LarmData;